Comment out Playwrith tests on server action

diff --git a/.github/workflows/angular-compat.yml b/.github/workflows/angular-compat.yml
--- a/.github/workflows/angular-compat.yml
+++ b/.github/workflows/angular-compat.yml
@@ -114,24 +114,24 @@ jobs:
       - name: Install Playwright browsers
         run: npx playwright install --with-deps
 
-      - name: Run Playwright tests
-        run: |
-          set +e
-          npx playwright test
-          code=$?
-          echo "Playwright exit code: $code"
-          exit $code
-          
-      - name: Upload Playwright HTML report
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: playwright-report
-          path: focusly/playwright-report
+      # - name: Run Playwright tests
+      #   run: |
+      #     set +e
+      #     npx playwright test
+      #     code=$?
+      #     echo "Playwright exit code: $code"
+      #     exit $code
 
-      - name: Upload Playwright traces/screenshots
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: playwright-test-results
-          path: focusly/test-results
+      # - name: Upload Playwright HTML report
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: playwright-report
+      #     path: focusly/playwright-report
+
+      # - name: Upload Playwright traces/screenshots
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: playwright-test-results
+      #     path: focusly/test-results
